//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuatTianYaHtmlMaker {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OuatTianYaHtmlMaker.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;Author&quot;: &quot;三语沫&quot;,
        ///    &quot;Title&quot;: &quot;[右岸文字]暗恋直女学妹的日子&quot;,
        ///    &quot;ChapterCount&quot;: 1,
        ///    &quot;Chapters&quot;: [
        ///        {
        ///            &quot;Time&quot;: &quot;2012-02-03 21:23&quot;,
        ///            &quot;Text&quot;: &quot;&lt;p&gt;第一次发贴，纯属打发时间，借此把那些不能再现实中倾诉的心路历程倾诉出来。&lt;/p&gt;&lt;p&gt;第一次见到她呢，远在七八年前，那时候她可叱咤风云了，高中的她喜欢穿白色飘逸的长裙，清丽婉约，袅袅婷婷，男生们都为她疯狂，每次她经过我们班的时候我们班那群就像炸开锅般吹口哨，起哄的什么的。&lt;/p&gt;&lt;p&gt;高中的我呢，是个女生眼中帅气的T,男生眼中不伦不类变态的T，融入不了小女生的世界，内向的我也怯于与男生交流，再加上男生大多不怎么接受打扮中性的女生的，所以那时候的我挺孤独的。&lt;/p&gt;&lt;p&gt;晚自习的课间我每天都会出来趴在走廊上的栏杆上透透气，有一天晚上，我突然再次听到男生们十分嘈杂的起哄声，厌恶之余转过身，却一眼撞见小跑而来她的目光，她蓦地停下脚步望着我，我还注意到她还抿紧了嘴唇，清 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML&gt;&lt;html&gt;&lt;head&gt;&lt;meta charset=&quot;utf-8&quot;/&gt;&lt;title&gt;{0}-{1}&lt;/title&gt;&lt;script type=&quot;text/javascript&quot;&gt;var alli=0;function getDocumentTop(){var scrollTop=0,bodyScrollTop=0,documentScrollTop=0;if(document.body){bodyScrollTop=document.body.scrollTop;}
        ///if(document.documentElement){documentScrollTop=document.documentElement.scrollTop;}
        ///scrollTop=(bodyScrollTop-documentScrollTop&gt;0)?bodyScrollTop:documentScrollTop;return scrollTop;}
        ///function getWindowHeight(){var windowHeight=0;if(document.compatMode==&quot;CSS1Com [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
    }
}
