//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuatTianYaHtmlMaker {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OuatTianYaHtmlMaker.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ3l0OGV1QnhhZHpjckQKQXptWThlNS84MDlCZEdsZm5ZYmZ5SlR2YkQ3RnUva3dzQ0dDOUdRdDRQcU93VmtBRUxxMURoWWs1VThickFkdwo4YkFQZWxaL0g2d3VTTURFdmd4Wm52ZDFRZ3NvR0QwcjhndFcrOUozeENBUnUraG1aaHdBWWU2dWpnYnpHM1FWCm1aYndjdmMxQi9uU1ZSNDFCalVVaEQ3NnRTZDRjVnovUmttRjFYV3J6VGVGbFFOenVJRWFjc0ZucWVDWkE5cGEKV2t1dkJtd3pGTC83NThpRXl0SHJWL2V2RzVFMDFZV2k3dmJxRjFjRUVETnpnY0d4RXpxMS9seEV6azJqd21ReAplTCtrdHRXdUVYMXpPUTF2RnZSd0h4WE9QZkFOcmxU [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RsaPublisher {
            get {
                return ResourceManager.GetString("RsaPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eyJDaGFwdGVycyI6W3siTnVtYmVyIjoiMCIsIlRpdGxlIjpudWxsLCJUaW1lIjoiMjAxMi0wMi0wMyAyMToyMyIsIlRleHQiOiI8cD7nrKzkuIDmrKHlj5HotLTvvIznuq/lsZ7miZPlj5Hml7bpl7TvvIzlgJ/mraTmiorpgqPkupvkuI3og73lho3njrDlrp7kuK3lgL7or4nnmoTlv4Pot6/ljobnqIvlgL7or4nlh7rmnaXjgII8L3A+PHA+56ys5LiA5qyh6KeB5Yiw5aW55ZGi77yM6L+c5Zyo5LiD5YWr5bm05YmN77yM6YKj5pe25YCZ5aW55Y+v5Y+x5ZKk6aOO5LqR5LqG77yM6auY5Lit55qE5aW55Zac5qyi56m/55m96Imy6aOY6YC455qE6ZW/6KOZ77yM5riF5Li95amJ57qm77yM6KKF6KKF5am35am377yM55S355Sf5Lus6YO95Li65aW555av54uC77yM5q+P5qyh5aW557uP [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Chapters {
            get {
                return ResourceManager.GetString("Template_Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PGJvZHk+CiAgICA8ZGl2IGNsYXNzPSJzaG93IiBpZD0ic2hvdyI+CiAgICAgICAgPHA+4piGPC9wPgogICAgPC9kaXY+CiAgICA8ZGl2PgogICAgICAgIDx0ZXh0YXJlYSBjbGFzcz0icHVicHJpa2V5IiBvbmJsdXI9InB1YnByaWtleSgpIiBpZD0icHJpdmtleSIgcm93cz0iMyIgY29scz0iNSI+IC0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLSAtLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tIDwvdGV4dGFyZWE+CiAgICAgICAgPHRleHRhcmVhIGNsYXNzPSJwdWJwcmlrZXkiIG9uYmx1cj0icHVicHJpa2V5KCkiIGlkPSJzaWducHVia2V5IiByb3dzPSIzIiBjb2xzPSI1Ij4gLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0gLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tIDwvdGV4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_Body {
            get {
                return ResourceManager.GetString("Template_Html_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHN0eWxlIHR5cGU9InRleHQvY3NzIj4KdGV4dGFyZWEucHVicHJpa2V5CnsKCXdpZHRoOjEwMCU7CgloZWlnaHQ6MTAwJTsKCWJvcmRlcjp0aGluIGRvdWJsZSAjOTA2OwoJdGV4dC1hbGlnbjpsZWZ0Owp9CgpwLkNoYXB0ZXJzCnsKCWNvbG9yOiNGRkVDQkY7CgliYWNrZ3JvdW5kLWNvbG9yOiNGRkIyMDA7CglkaXNwbGF5OmJsb2NrOwoJdmlzaWJpbGl0eTp2aXNpYmxlOwoJY3Vyc29yOnBvaW50ZXI7Cglib3JkZXI6MnB4IHNvbGlkICNGRkIyMDA7Cglmb250LXNpemU6MmVtOwoJdGV4dC1hbGlnbjpjZW50ZXI7CgltYXJnaW46MCBhdXRvOwp9CgpwLkF1dGhvcgp7Cgljb2xvcjojRkZCMjAwOwoJYmFja2dyb3VuZC1jb2xvcjojRkZFQ0JGOwoJZGlzcGxheTpibG9jazsKCXZp [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_CSS {
            get {
                return ResourceManager.GetString("Template_Html_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCFET0NUWVBFIEhUTUw+CjxodG1sPgo8aGVhZD4KCTxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgoJPHNjcmlwdD48L3NjcmlwdD4KCTxzdHlsZT48L3N0eWxlPgoJPHRpdGxlPjwvdGl0bGU+CjwvaGVhZD4KPEJvZHk+PC9Cb2R5Pgo8L2h0bWw+Cg== 的本地化字符串。
        /// </summary>
        internal static string Template_Html_Html {
            get {
                return ResourceManager.GetString("Template_Html_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PGJvZHk+CiAgICA8ZGl2IGNsYXNzPSJzaG93IiBpZD0ic2hvdyI+CiAgICAgICAgPHA+4piGPC9wPgogICAgPC9kaXY+CiAgICA8ZGl2PgogICAgICAgIDx0ZXh0YXJlYSBjbGFzcz0icHVicHJpa2V5IiBvbmJsdXI9InB1YnByaWtleSgpIiBpZD0icHJpdmtleSIgcm93cz0iMyIgY29scz0iNSI+IC0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLSAtLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tIDwvdGV4dGFyZWE+CiAgICAgICAgPHRleHRhcmVhIGNsYXNzPSJwdWJwcmlrZXkiIG9uYmx1cj0icHVicHJpa2V5KCkiIGlkPSJzaWducHVia2V5IiByb3dzPSIzIiBjb2xzPSI1Ij4gLS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0gLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tIDwvdGV4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_Script {
            get {
                return ResourceManager.GetString("Template_Html_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ewogICAgIkF1dGhvck5hbWUiOiAi5LiJ6K+t5rKrIiwKICAgICJBdXRob3JQdWJLZXkiOiAicHVia2V5IiwKCSJQdWJsaXNoZXJQdWJLZXkiOiJMUzB0TFMxQ1JVZEpUaUJRVlVKTVNVTWdTMFZaTFMwdExTMEtUVWxKUWtscVFVNUNaMnR4YUd0cFJ6bDNNRUpCVVVWR1FVRlBRMEZST0VGTlNVbENRMmRMUTBGUlJVRnpjbVpJY21kalYyNWpNMHQzZDAwMWJWQklkUXBtTDA1UVVWaFNjRmcxTWtjek9HbFZOekozSzNoaWRqVk5URUZvWjNaU2EweGxSRFpxYzBaYVFVSkROblJSTkZkS1QxWlFSelozU0dOUVIzZEVNM0JYQ21aNEszTk1hMnBCZUV3MFRWZGFOek5rVlVsTVMwSm5PVXN2U1V4V2RuWlRaRGhSWjBWaWRtOWFiVmxqUVVkSWRYSnZORWM0ZUhRd1JscHRWemhJVERNS1RsRm1O [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Info {
            get {
                return ResourceManager.GetString("Template_Info", resourceCulture);
            }
        }
    }
}
