//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OuatTianYaHtmlMaker {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OuatTianYaHtmlMaker.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtp
        ///Rzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURIUnEyNXNwSWVLMXQrDQpv
        ///M1BKOFhWQXdWVXlUV3dKL3hNRVFjWnU3ckRjcWxsSzJVbkdCS3ZPNUJTcmJ0TCt6
        ///aVBvSlJxZG54cE1KV29sDQpNMG4xdXZYbmF6bDFPQ0Q3M0RJbEVTMnQzY2dLN3E1
        ///bFR1V09rWVgwN29CTDUwamtqaGgzTGorTmdPTWZxL0FQDQpkOEpnc1NpSi92SzVs
        ///bC83NFRkeW5yNG9vVkV4dDRVcEJmRzVQbkoyT2NpeVJBYmFCRUZaUS9zQVFpcnRI
        ///V3RsDQpjTmVPem5CRUtsTXR3OFErUC9ROE1ZYXpFK2g5THl2ZG13Y0swWnBCQlJ2
        ///TVJRM0x0WW91RllGaUgzWW4vWWVODQoxZ0sxNlpNTDlvcXlWelg1Ny9aM [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RsaPublisher {
            get {
                return ResourceManager.GetString("RsaPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ww0KICB7DQogICAgIk5vIjogIjEiLA0KICAgICJUaXRsZSI6ICJUaXRsZTEiLA0KICAgICJUaW1lIjogIjIwMjHlubQz5pyINOaXpTA554K5NDHliIYiLA0KICAgICJUZXh0IjogIlRleHQxIiwNCiAgICAiUmVhZGVycyI6IFsNCiAgICAgIHsNCiAgICAgICAgIk5hbWUiOiAiUmVhZGVyczExIiwNCiAgICAgICAgIlRpbWUiOiAidmFsdWUxMSIsDQogICAgICAgICJSZXBseSI6ICJ2YWx1ZTExIg0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIk5hbWUiOiAiUmVhZGVyczEyIiwNCiAgICAgICAgIlRpbWUiOiAidmFsdWUxMiIsDQogICAgICAgICJSZXBseSI6ICJ2YWx1ZTEyIg0KICAgICAgfSwNCiAgICAgIHsNCiAgICAgICAgIk5hbWUiOiAiUmVhZGVyczEzIiwNCiAgICAg [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Chapters {
            get {
                return ResourceManager.GetString("Template_Chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 W3siTnVtYmVyIjoiMCIsIkV0ZXh0IjoiTCtyUlNVUHRMeU5SL0ZIUTIxaFJPWFNoNk10ZFlUWExUcFV2YUVJMXRROGpSSzZSNlBhU3NSRFhGOWZQckRoYzBXVVFmM2Ixa0JCZVc2Tm8xSmpvMkMxeWl5YjdWSmNyeGNUd1JJbXI4MFhpTS9aWVZZclR5QXhjWCtxYXdXanphTFpaWjJhSm1BaHZRdkdrMXZ6aldreFgyd1BhTTNYTzh1ZXFFTWY1eU9udTc5ekh4KzcrRUMxQnRjei9KQnpMUmwvQzhpTS9FOG5VbUdiR1FrZWlod004bzdnSm1pRC9YR3JIVlFvd2REeFFDWXIxYWpWajZSZ2sxOHZCMGNQVGdaaVdBejlqQ0VHMFN4Uit0bUZRanNnUmxWUVoxSkpxcTQ5L1Nka2Z3OUpVQkpDNEI4bTNnbnJBV1ZBVXZJQnh6SUMvUU81aWFTSDRNZGdXUDFtUGtoOFd4VytnTS9VY2FTUFQ4eWMx [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_EncryptChapters_MochajoeBook {
            get {
                return ResourceManager.GetString("Template_EncryptChapters_MochajoeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PGJvZHkgb25yZXNpemU9Im9ucmVzaXplKCkiPg0KCTxkaXYgY2xhc3M9InNob3ciIGlkPSJzaG93IiBvbmNsaWNrPSJzaG93UmVhZGluZ1Byb2dyZXNzKCkiPg0KCQk8cD7imIY8L3A+DQoJPC9kaXY+DQoJPGRpdj4NCgkJPHRleHRhcmVhIGNsYXNzPSJwdWJwcmlrZXkiIG9uYmx1cj0icHVicHJpa2V5KCkiIGlkPSJwcml2a2V5IiByb3dzPSIzIiBjb2xzPSI1Ij4gLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tIC0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0gDQoJCTwvdGV4dGFyZWE+DQoJCTx0ZXh0YXJlYSBjbGFzcz0icHVicHJpa2V5IiBvbmJsdXI9InB1YnByaWtleSgpIiBpZD0ic2lnbnB1YmtleSIgcm93cz0iMyIgY29scz0iNSI+IC0tLS0tQkVHSU4gUFVCTElDIEtF [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_Body {
            get {
                return ResourceManager.GetString("Template_Html_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHN0eWxlIHR5cGU9InRleHQvY3NzIj4NCgl0ZXh0YXJlYS5wdWJwcmlrZXkgew0KCQl3aWR0aDogMTAwJTsNCgkJaGVpZ2h0OiAxMDAlOw0KCQlib3JkZXI6IHRoaW4gZG91YmxlICM5MDY7DQoJCXRleHQtYWxpZ246IGxlZnQ7DQoJfQ0KDQoJcC5DaGFwdGVycyB7DQoJCWNvbG9yOiAjRkZFQ0JGOw0KCQliYWNrZ3JvdW5kLWNvbG9yOiAjRkZCMjAwOw0KCQlkaXNwbGF5OiBibG9jazsNCgkJdmlzaWJpbGl0eTogdmlzaWJsZTsNCgkJY3Vyc29yOiBwb2ludGVyOw0KCQlib3JkZXI6IDJweCBzb2xpZCAjRkZCMjAwOw0KCQlmb250LXNpemU6IDJlbTsNCgkJdGV4dC1hbGlnbjogY2VudGVyOw0KCQltYXJnaW46IDAgYXV0bzsNCgl9DQoNCglwLkF1dGhvciB7DQoJCWNvbG9yOiAj [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_CSS {
            get {
                return ResourceManager.GetString("Template_Html_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCFET0NUWVBFIEhUTUw+CjxodG1sPgo8aGVhZD4KCTxtZXRhIGNoYXJzZXQ9InV0Zi04IiAvPgoJPHNjcmlwdD48L3NjcmlwdD4KCTxzdHlsZT48L3N0eWxlPgoJPHRpdGxlPjwvdGl0bGU+CjwvaGVhZD4KPEJvZHk+PC9Cb2R5Pgo8L2h0bWw+Cg== 的本地化字符串。
        /// </summary>
        internal static string Template_Html_Html {
            get {
                return ResourceManager.GetString("Template_Html_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CTxzY3JpcHQgc3JjPSIgaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9jcnlwdG8tanNANC4wLjAvY3J5cHRvLWpzLmpzIj4NCgk8L3NjcmlwdD4NCgk8c2NyaXB0IHNyYz0iaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9qc2VuY3J5cHRAMy4wLjAtcmMuMS9iaW4vanNlbmNyeXB0LmpzIj4NCgk8L3NjcmlwdD4NCg0KCTxzY3JpcHQgdHlwZT0idGV4dC9qYXZhc2NyaXB0Ij4NCgkJLy8gbW9jaGFqb2UyMDIxICAyMDIx5bm0M+aciDIy5pelMjHngrkxNeWIhg0KCQkvL21vY2hham9lMjAyMSAyMDIx5bm0M+aciDIz5pelMDDngrkxN+WIhg0KCQl2YXIgbW9jaGFqb2Vib29rID0gIiI7DQoJCXZhciBDaGFwdGVyQ291bnQgPSAwOw0KCQl2YXIgcHJpdmtleSA9ICIiOw0K [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_Script {
            get {
                return ResourceManager.GetString("Template_Html_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PHNjcmlwdCB0eXBlPSJ0ZXh0L2phdmFzY3JpcHQiPg0KLy9jcnlwdG8tanNANC4wLjAvY3J5cHRvLWpzLmpzDQo7KGZ1bmN0aW9uIChyb290LCBmYWN0b3J5KSB7DQoJaWYgKHR5cGVvZiBleHBvcnRzID09PSAib2JqZWN0Iikgew0KCQkvLyBDb21tb25KUw0KCQltb2R1bGUuZXhwb3J0cyA9IGV4cG9ydHMgPSBmYWN0b3J5KCk7DQoJfQ0KCWVsc2UgaWYgKHR5cGVvZiBkZWZpbmUgPT09ICJmdW5jdGlvbiIgJiYgZGVmaW5lLmFtZCkgew0KCQkvLyBBTUQNCgkJZGVmaW5lKFtdLCBmYWN0b3J5KTsNCgl9DQoJZWxzZSB7DQoJCS8vIEdsb2JhbCAoYnJvd3NlcikNCgkJcm9vdC5DcnlwdG9KUyA9IGZhY3RvcnkoKTsNCgl9DQp9KHRoaXMsIGZ1bmN0aW9uICgpIHsNCg0KCS8qZ2xv [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Html_ScriptAllinOn {
            get {
                return ResourceManager.GetString("Template_Html_ScriptAllinOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ew0KICAgICJBdXRob3JOYW1lIjogIuS4ieivreayqyIsDQogICAgIkF1dGhvclB1YktleSI6ICJwdWJrZXkiLA0KCSJQdWJsaXNoZXJQdWJLZXkiOiJMUzB0TFMxQ1JVZEpUaUJRVlVKTVNVTWdTMFZaTFMwdExTME5DazFKU1VKSmFrRk9RbWRyY1docmFVYzVkekJDUVZGRlJrRkJUME5CVVRoQlRVbEpRa05uUzBOQlVVVkJlREJoZEhWaVMxTklhWFJpWm5GT2VubG1SakVOQ2xGTlJsWk5hekZ6UTJZNFZFSkZTRWRpZFRaM00wdHdXbE4wYkVwNFoxTnllblZSVlhFeU4xTXZjelJxTmtOVllXNWFPR0ZVUTFaeFNsUk9TamxpY2pFTkNqVXljelZrVkdkbkt6bDNlVXBTUlhSeVpETkpRM1UyZFZwVk4yeHFjRWRHT1U4MlFWTXJaRWsxU1RSWlpIazBMMnBaUkdwSU5uWjNSRE5tUTFsTVJX [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Template_Info {
            get {
                return ResourceManager.GetString("Template_Info", resourceCulture);
            }
        }
    }
}
